<Project>
  <PropertyGroup>
    <Version>0.0.0-dev</Version>
    <Company>Tyrrrz</Company>
    <Copyright>Copyright (C) Oleksii Holub</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>$(Company)</Authors>
    <Description>MSBuild extension that lets you internalize package and project references by merging them into the output assembly as internal APIs</Description>
    <PackageTags>msbuild ilmerge ilrepack internalize dependencies</PackageTags>
    <PackageProjectUrl>https://github.com/Tyrrrz/Binternal</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/Tyrrrz/Binternal/releases</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
