<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <Target
    Name="Binternal_InternalizeAfterBuild"
    AfterTargets="Build"
    Condition="'$(TargetPath)' != ''"
  >
    <InternalizationTask
      PackageReferences="@(PackageReference)"
      ProjectReferences="@(ProjectReference)"
      ReferencedAssemblies="@(ReferenceCopyLocalPaths);@(RuntimeCopyLocalItems)"
      TargetFilePath="$(TargetPath)"
      KeyFilePath="$(AssemblyOriginatorKeyFile)"
      DelaySign="$(DelaySign)"
    />
  </Target>

  <Target
    Name="Binternal_InternalizeAfterPublish"
    AfterTargets="Publish"
    Condition="'$(PublishDir)' != ''"
  >
    <InternalizationTask
      PackageReferences="@(PackageReference)"
      ProjectReferences="@(ProjectReference)"
      ReferencedAssemblies="@(ReferenceCopyLocalPaths);@(RuntimeCopyLocalItems)"
      TargetFilePath="$([System.IO.Path]::Combine('$(ProjectDir)', '$(PublishDir)/$(AssemblyName).dll'))"
      KeyFilePath="$(AssemblyOriginatorKeyFile)"
      DelaySign="$(DelaySign)"
    />
  </Target>
</Project>
