<Project Sdk="Microsoft.NET.Sdk">
  <!-- Props/targets are automatically imported by NuGet, but here we need to do it manually. -->
  <!-- This needs to be done before any other props or targets, to match NuGet's behavior. -->
  <Import Project="../Binternal/Binternal.Local.props" />
  <Import Project="../Binternal/Binternal.targets" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netstandard2.0;net472;net6.0;net7.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpier.MSBuild" PrivateAssets="all" />
    <PackageReference Include="PolyShim" PrivateAssets="all" />

    <!-- Package A: internalized -->
    <PackageReference
      Include="Microsoft.Extensions.Http.Polly"
      Internalize="true"
      PrivateAssets="all"
    />

    <!-- Package B: direct, not internalized (also transitive through package A) -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />

    <!-- Make sure strong naming is preserved after internalization -->
    <PackageReference Include="Snek" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Binternal/Binternal.csproj" />
  </ItemGroup>
</Project>
