<Project
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
  ToolsVersion="4.0"
>
  <!-- Run after the build to inline marked package references -->
  <Target
    Name="_BinlineMerge"
    AfterTargets="Build"
    Condition="@(PackageReference->WithMetadataValue('Inline', 'true')->Count()) > 0"
  >
    <BinlineTask
      TargetAssembly="$(TargetPath)"
      PackageReferences="@(PackageReference)"
      ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
    />
  </Target>
</Project>
